pub mod api;
pub mod artifacts;
pub mod auth;
pub mod build_executor;
pub mod builder;
pub mod config;
pub mod db;
pub mod detector;
pub mod framework;
pub mod model;
pub mod providers;
pub mod queue;
pub mod repository;
pub mod runtime;
pub mod service;
pub mod source_checkout;
pub mod source_events;
pub mod store;
pub mod webhooks;

pub type Result<T> = anyhow::Result<T>;
